import { useMemo, useRef } from 'react'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'

import { cn } from '@/lib/utils'

gsap.registerPlugin(useGSAP)

type KeyboardBackgroundProps = {
  className?: string
}

export function KeyboardBackground({ className }: KeyboardBackgroundProps) {
  const svgRef = useRef<SVGSVGElement | null>(null)

  useGSAP(
    () => {
      const keys =
        svgRef.current?.querySelectorAll<SVGRectElement>('.key-stroke')

      if (!keys || keys.length === 0) return

      gsap.fromTo(
        keys,
        {
          opacity: 0,
          y: 16,
          scale: 0.9,
        },
        {
          opacity: 1,
          y: 0,
          scale: 1,
          duration: 1.4,
          ease: 'power3.out',
          stagger: {
            each: 0.04,
            from: 'random',
          },
        },
      )
    },
    { scope: svgRef },
  )

  const wrapperClassName = useMemo(
    () =>
      cn(
        'absolute inset-0 z-0 flex items-center justify-center opacity-[0.05] pointer-events-none overflow-hidden select-none',
        className,
      ),
    [className],
  )

  return (
    <div className={wrapperClassName}>
      <svg
        ref={svgRef}
        className="w-[140%] h-auto -rotate-12 text-ink animate-[pulse_8s_ease-in-out_infinite]"
        viewBox="0 0 800 350"
        xmlns="http://www.w3.org/2000/svg"
        preserveAspectRatio="xMidYMid meet"
      >
        <rect
          x="10"
          y="10"
          width="780"
          height="300"
          rx="15"
          className="key-stroke"
        />

        <g transform="translate(25, 25)">
          <rect
            x="0"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="65"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="115"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="165"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="215"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="280"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="330"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="380"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="430"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="495"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="545"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="595"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="645"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="705"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
        </g>

        <g transform="translate(25, 80)">
          <rect
            x="0"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="50"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="100"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="150"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="200"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="250"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="300"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="350"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="400"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="450"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="500"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="550"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="600"
            y="0"
            width="95"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="705"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
        </g>

        <g transform="translate(25, 130)">
          <rect
            x="0"
            y="0"
            width="70"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="75"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="125"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="175"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="225"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="275"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="325"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="375"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="425"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="475"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="525"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="575"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="625"
            y="0"
            width="70"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="705"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
        </g>

        <g transform="translate(25, 180)">
          <rect
            x="0"
            y="0"
            width="85"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="90"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="140"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="190"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="240"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="290"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="340"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="390"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="440"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="490"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="540"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="590"
            y="0"
            width="105"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="705"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
        </g>

        <g transform="translate(25, 230)">
          <rect
            x="0"
            y="0"
            width="110"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="115"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="165"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="215"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="265"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="315"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="365"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="415"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="465"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="515"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="565"
            y="0"
            width="80"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="655"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
        </g>

        <g transform="translate(25, 280)">
          <rect
            x="0"
            y="0"
            width="55"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="60"
            y="0"
            width="55"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="120"
            y="0"
            width="55"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="180"
            y="0"
            width="280"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="465"
            y="0"
            width="55"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="525"
            y="0"
            width="55"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="605"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="655"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
          <rect
            x="705"
            y="0"
            width="45"
            height="45"
            rx="4"
            className="key-stroke"
          />
        </g>
      </svg>
    </div>
  )
}
